### ISSUE TITLE
Docker containers are up.

### ISSUE THREAD

**Issue by gogillu** [openstf/stf#1181]
**What is the issue or idea you have?**

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

**Please provide the steps to reproduce the issue.**

**What is the expected behavior?**

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

**Please run `stf doctor` and paste the output here.**

**Comment by gogillu** [comment]
Finally after a lot of efforts, found out the simple mistake.
Still not able to setup Provider with docker but able to do it with direct command line.

Thabks to [this](https://www.gitmemory.com/denis99999)

--bind-dev-pub
--bind-dev-pull

mentioned these parameters as shown on the link and then able to see all the devices via master server.

:)

**Comment by gogillu** [comment]
Still if someone can help with docker it will be good.

Thankyou

**Comment by koral--** [comment]
Are you sure that rethinkdb instance is running properly? Is its web console available on port 8080?

**Comment by gogillu** [comment]
Yes,

I am able to access rethinkdb from browser,
on 8080

**Comment by denis99999** [comment]
@gogillu,
Try something like that, it should work:

`docker-compose.yml:`
```
version: "2.0"
services:
  rethinkdb:
    image: rethinkdb:2.3
    network_mode: host
    restart: always
    volumes:
      - "/Users/gchoudhary/Documents/Projects/rethinkdb:/data"
    command: "rethinkdb --bind all"

  adbd:
    image: sorccu/adb
    privileged: true
    network_mode: host
    restart: always

  stf:
    image: openstf/stf
    depends_on:
      - rethinkdb
      - adbd
    network_mode: host
    restart: always
    command: "stf local --public-ip 10.4.215.90"
```
`% docker-compose up`
