### ISSUE TITLE
/api/v1/devices 404

### ISSUE THREAD

**Issue by wchensc** [openstf/stf#1210]
**What is the issue or idea you have?**
I am using docker compose to setup the env. The ui rendered correctly. But it didn't have any devices showing up. When I check the console, it indicated as "/api/v1/devices" 404.

<img width="1673" alt="Screen Shot 2020-03-23 at 3 54 49 PM" src="https://user-images.githubusercontent.com/22922463/77370840-fd0aa080-6d1e-11ea-9f8d-4eb713b16302.png">

Here are my config files:
### nginx:
```
#daemon off
worker_processes 4;

events {
  worker_connections 1024;
}

http {
  upstream stf_app {
    server 10.52.32.114:3100 max_fails=0;
  }

  upstream stf_auth {
    server 10.52.32.114:3101 max_fails=0;
  }

  upstream stf_storage_apk {
    server 10.52.32.114:3102 max_fails=0;
  }

  upstream stf_storage_image {
    server 10.52.32.114:3103 max_fails=0;
  }

  upstream stf_storage {
    server 10.52.32.114:3104 max_fails=0;
  }

  upstream stf_websocket {
    server 10.52.32.114:3105 max_fails=0;
  }

  upstream stf_api {
    server 10.52.32.114:3106 max_fails=0;
  }

  types {
    application/javascript  js;
    image/gif               gif;
    image/jpeg              jpg;
    text/css                css;
    text/html               html;
  }

  map $http_upgrade $connection_upgrade {
    default  upgrade;
    ''       close;
  }

  server {
    listen 80;
    server_name 10.52.32.114;
    keepalive_timeout 70;
#    resolver 114.114.114.114 8.8.8.8 valid=300s;
#    resolver_timeout 10s;
location ~ "^/d/provider1/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.52.32.114:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ "^/d/provider2/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://10.52.32.64:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
      proxy_pass http://stf_auth/auth/;
    }

    location /api/ {
      proxy_pass http://stf_api/api/;
    }

    location /s/image/ {
      proxy_pass http://stf_storage_image;
    }

    location /s/apk/ {
      proxy_pass http://stf_storage_apk;
    }

    location /s/ {
      client_max_body_size 1024m;
      client_body_buffer_size 128k;
      proxy_pass http://stf_storage;
    }

    location /socket.io/ {
      proxy_pass http://stf_websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }

    location / {
      proxy_pass http://stf_app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $http_x_real_ip;
    }
  }
}
```

### stf-app docker-compose.yml
```
version: '3'
services:
  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - /data/stf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host"

  rethinkdb:
    depends_on:
      - nginx
    image: rethinkdb:2.3.6
    command: rethinkdb --bind all --cache-size 8192 --http-port 8090 --no-update-check
    volumes:
      - /data/stf/rethinkdb:/data
    network_mode: "host"

  stf-migrate:
    depends_on:
      - rethinkdb
    image: $STF_IMAGE
    command: stf migrate
    network_mode: "host"

  stf-app:
    depends_on:
      - stf-migrate
    image: $STF_IMAGE
    command: stf app --port 3100 --auth-url ${STF_URL}/auth/mock/ --websocket-url ws://${STF_HOST}/
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-auth:
    depends_on:
      - stf-app
    image: $STF_IMAGE
    command: stf auth-mock --port 3101 --app-url ${STF_URL}
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-storage-plugin-apk:
    depends_on:
      - stf-api
    image: $STF_IMAGE
    command: stf storage-plugin-apk --port 3102 --storage-url ${STF_URL}
    network_mode: "host"

  stf-storage-plugin-image:
    depends_on:
      - stf-storage-plugin-apk
    image: $STF_IMAGE
    command: stf storage-plugin-image --port 3103 --storage-url $STF_URL
    network_mode: "host"

  stf-storage-temp:
    depends_on:
      - stf-storage-plugin-image
    image: $STF_IMAGE
    command: stf storage-temp --port 3104 --save-dir /tmp
    network_mode: "host"
stf-websocket:
    depends_on:
      - stf-auth
    image: $STF_IMAGE
    command: stf websocket --port 3105 --storage-url $STF_URL --connect-sub tcp://$STF_HOST:7150 --connect-push tcp://$STF_HOST:7170
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-api:
    depends_on:
      - stf-websocket
    image: $STF_IMAGE
    command: stf api --port 3106 --connect-sub tcp://$STF_HOST:7150 --connect-push tcp://$STF_HOST:7170
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-triproxy-app:
    depends_on:
      - stf-storage-temp
    image: $STF_IMAGE
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    network_mode: "host"

  stf-processor:
    depends_on:
      - stf-triproxy-app
    image: $STF_IMAGE
    command: stf processor stf-processer --connect-app-dealer tcp://$STF_HOST:7160 --connect-dev-dealer tcp://$STF_HOST:7260
    network_mode: "host"

  stf-triproxy-dev:
    depends_on:
      - stf-processor
    image: $STF_IMAGE
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    network_mode: "host"

  stf-reaper:
    depends_on:
      - stf-triproxy-dev
    image: $STF_IMAGE
    command: stf reaper dev --connect-push tcp://$STF_HOST:7270 --connect-sub tcp://$STF_HOST:7150 --heartbeat-timeout 30000
    network_mode: "host"

  stf-log-rethinkdb:
    depends_on:
      - stf-reaper
    image: $STF_IMAGE
    command: stf log-rethinkdb --connect-sub tcp://devside.$STF_HOST:7150
    network_mode: "host"
```

### STF provider docker-compose.yml
```
version: '3'
services:
  stf-provider:
    image: $STF_IMAGE
    command: stf provider --name "${STF_PROVIDER}" --connect-sub tcp://$STF_HOST:7250 --connect-push tcp://$STF_HOST:7270 --storage-url $STF_URL --public-ip $STF_PROVIDER.$STF_HOST --min-port=15000 --max-port=25000 --heartbeat-interval 20000 --screen-ws-url-pattern "ws://${STF_HOST}/d/${STF_PROVIDER}/<%= serial %>/<%= publicPort %>/"
    network_mode: "host"
```
