### ISSUE TITLE
How to set up to login by password/SSO?

### ISSUE THREAD

**Issue by EdenLyf** [openstf/stf#1351]
A great platform that I can using to manage the test devices in our team easily.

I have set up the platform by Docker container, and I have set up`stf/docker-compose.yaml` like this, so I can login by Name and Email.

 I'm confused with the 2 questions,
1. I want to login by Email and password, what else and where I need to set up?
2. If we want to using the Google email in our team to login by SSO, is it supported, how and where I need to set up?

```
version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    ports:
      - "8080:8080"
      - "28015:28015"
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  stf:
    container_name: stf
    image: devicefarmer/stf
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=my_email
      - STF_ADMIN_NAME=my_username
      - STF_ROOT_GROUP_NAME=my_group
    restart: unless-stopped
    command: stf local --adb-host host.docker.internal --public-ip my_ip_address --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
```

![stf1](https://github.com/openstf/stf/assets/92203756/c059ae64-3be3-4e8c-9c45-30b7ecfd6256)
