### ISSUE TITLE
docker setup guide

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [openstf/stf#374]
I was wondering if someone can update the documentation to get STF setup using docker, I have seen the current doc's and it's slightly confusing to people who never used docker before. I have got STF running on a mac very easily via the terminal, but would like a similar guide on setting up STF docker container via the terminal.

**Comment by Allsimon** [comment]
Yup, a setup guide would be nice... I tried with this `docker-compose.yml`:
```
rethinkdb:
    image: rethinkdb

openstf:
    image: openstf/stf
    links:
        - rethinkdb
    ports:
        - "7100:7100"
        - "7110:7110"
    command: stf local
```
I get access to the login page at `http://localhost:7100`, can login, but I'm stuck with the `No devices connected` message (I tried 3 different devices, adb works fine but stf doesn't seems to find them). Did I miss something ?

**Comment by mirceanis** [comment]
Hi,
There must be a good reason people keep saying `stf local` is not meant for docker.
However, I've managed to put together a `docker-compose.yml` that seems to work.

```
rethinkdb:
  image: rethinkdb:2.3
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  restart: always
  volumes:
    - "/srv/rethinkdb:/data"
  command: "rethinkdb --bind all --cache-size 2048"

adbd:
  image: sorccu/adb
  privileged: true
  ports:
    - "5037:5037"
  restart: always
  volumes:
    - "/dev/bus/usb:/dev/bus/usb"

stf-local:
  image: openstf/stf
  links:
    - rethinkdb
    - adbd
  ports:
    - "7100:7100"
    - "7110:7110"
    - "7120:7120"
    - "7400-7500:7400-7500"
  restart: always
  command: stf local --public-ip 192.168.1.127 --provider-min-port 7400 --provider-max-port 7500 --adb-host adbd
```

Obviously, you'll have to replace the `--public-ip` from the last line with the IP address of your docker host.

With this setup, I'm able to access my devices by going to http://192.168.1.127:7100

I hope it helps
