### ISSUE TITLE
Atfer LDAP implementation, an user can not access to the phone.

### ISSUE THREAD

**Issue by sonamoo** [openstf/stf#908]
**What is the issue or idea you have?**
I just changed the auth setting from mock to LDAP since our team wanted this way. But after switching to LDAP, an logged in user can not access to the smartphone. An user can log in, and provider could recognize the device, but when I click the 'use' button, I get "Socket connection was lost" message.

**Please provide the steps to reproduce the issue.**
I am using Docker Compose to run

here is the docker-compose segment that is related to this issue

```
app:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf app --auth-url http://${PUBLIC_IP}/auth/ldap/ --websocket-url ws://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
  auth:
    image: openstf/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
    command:
      stf auth-ldap --app-url http://${PUBLIC_IP}/ --port 3000 \
      stf auth-ldap --ldap-search-dn ou=people,ou=intranet,dc=motorola,dc=com \
      stf auth-ldap --ldap-search-field uid \
      stf auth-ldap --ldap-url ldap://ids.mot-solutions.com:389 


```
**Error message when I toggle 'use' button on the pannel.**

Here are the logs when I try to use the device.
```
nginx_1                 | 10.2.114.41 - - [11/Jul/2018:14:38:58 +0000] "GET /static/app/devices/icon/x24/E30HT.jpg HTTP/1.1" 304 0 "http://stf.am.mot-solutions.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
nginx_1                 | 10.2.114.41 - - [11/Jul/2018:14:38:58 +0000] "GET /static/app/build/fda02a702c4a73c27958341c42582645.png HTTP/1.1" 304 0 "http://stf.am.mot-solutions.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
websocket_1             | /app/node_modules/protobufjs/dist/ProtoBuf.js:2641
websocket_1             |                     throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");
nginx_1                 | 10.2.114.41 - - [11/Jul/2018:14:38:58 +0000] "GET /socket.io/?uip=10.2.114.41&EIO=3&transport=websocket HTTP/1.1" 101 122 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
websocket_1             |                     ^
websocket_1             | 
websocket_1             | Error: Illegal value for Message.Field .OwnerMessage.name of type string: object (no array expected)
websocket_1             |     at Error (native)
websocket_1             |     at T.<anonymous> (/app/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
websocket_1             |     at T.ProtoBuf.Reflect.FieldPrototype.verifyValue (/app/node_modules/protobufjs/dist/ProtoBuf.js:2659:21)
websocket_1             |     at MessagePrototype.set (/app/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
websocket_1             |     at Message (/app/node_modules/protobufjs/dist/ProtoBuf.js:1728:42)
websocket_1             |     at Socket.<anonymous> (/app/lib/units/websocket/index.js:683:17)
websocket_1             |     at emitThree (events.js:116:13)
websocket_1             |     at Socket.emit (events.js:194:7)
websocket_1             |     at /app/node_modules/socket.io/lib/socket.js:528:12
websocket_1             |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
websocket_1             |     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Please run `stf doctor` and paste the output here.**

Here are the results when I run `stf doctor` on websocket container.  I have Rethink Cluster running. I am wondering if this is happening because of ProtoBuf is not installed inside of the websocket container. But the error messages point to the ProtoBuf.js path. I don't know what is causing this disconnection error. 
```
2018-07-11T14:37:46.011Z INF/cli:doctor 58 [*] OS Arch: x64
2018-07-11T14:37:46.013Z INF/cli:doctor 58 [*] OS Platform: linux
2018-07-11T14:37:46.014Z INF/cli:doctor 58 [*] OS Platform: 4.13.0-46-generic
2018-07-11T14:37:46.014Z INF/cli:doctor 58 [*] Using Node 6.11.2
2018-07-11T14:37:46.034Z INF/cli:doctor 58 [*] Using ZeroMQ 4.1.4
2018-07-11T14:37:46.057Z INF/cli:doctor 58 [*] Using GraphicsMagick 1.3.23
2018-07-11T14:37:46.058Z ERR/cli:doctor 58 [*] RethinkDB is not installed (`rethinkdb` is missing)
2018-07-11T14:37:46.059Z ERR/cli:doctor 58 [*] ProtoBuf is not installed (`protoc` is missing)
2018-07-11T14:37:46.059Z ERR/cli:doctor 58 [*] ADB is not installed (`adb` is missing)

```
